# ###
# GET http://localhost:3000

###
GET http://localhost:3000/ciclo/listar

###
GET http://localhost:3000/ciclo/listar/:x10/:y20/:z30

###
POST http://localhost:3000/ciclo/cadastrar
Content-Type: application/json

{
    "titulo": "Dota 2",
    "plataforma": "PC",
    "valor": 50.99,
    "genero": "Moba"
}
